version: '3'
services:
    next.dev:
        build:
          context: .
          dockerfile: Dockerfile.development
        ports:
            - '3000:3000'
        volumes:
            - '.:/app'
        command: ash -c "npm install && npm run dev"

