version: '3'
services:
    laravel.dev:
        build:
            context: ./api
            dockerfile: docker/Dockerfile.development
        image: sail-8.0/app
        env_file:
          - ./api/.env
          - .env
        ports:
            - '80:80'
        volumes:
            - './api:/var/www/html:delegated'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        command: bash -c 'php artisan config:cache&& /usr/bin/php -d variables_ordder=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80'
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './mysql/data:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sail
    next.dev:
        build:
          context: ./next
          dockerfile: docker/Dockerfile.development
        ports:
            - '3000:3000'
        networks:
            - sail
        volumes:
            - './next:/app'
        command: ash -c "npm install && npm run dev"
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local

