version: '3'
services:
    laravel.prod:
        build:
            context: ./api
            dockerfile: docker/Dockerfile.production
        image: sail-8.0/app
        ports:
            - '80:80'
        volumes:
            - './api:/var/www/html:delegated'
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './mysql/data:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - './redis/data:/data'
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        volumes:
            - './meilisearch/data:/data.ms'
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        command: ["-storage=maildir", "-maildir-path=/maildir"]
        volumes:
            - ./mailhog/data:/maildir
    next.prod:
        build:
          context: ./next
          dockerfile: docker/Dockerfile.production
        ports:
            - '3000:3000'

