version: '3'
services:
    laravel.dev:
        build:
            context: ./api
            dockerfile: docker/Dockerfile.development
            args:
                APP_PORT: '80'
                APP_SERVICE: 'laravel.dev'
                DB_PORT: '3306'
        image: sail-8.0/app
        env_file:
          - ./api/.env
          - .env
        ports:
            - '80:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - './api:/var/www/html:delegated'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        command: bash -c 'php artisan config:cache&& /usr/bin/php -d variables_ordder=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80'
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        env_file:
            - ./api/.env
            - .env
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        env_file:
            - ./api/.env
            - .env
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        env_file:
            - ./api/.env
            - .env
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        env_file:
            - ./api/.env
            - .env
        networks:
            - sail
    next.dev:
        build:
          context: ./next
          dockerfile: docker/Dockerfile.development
        ports:
            - '3000:3000'
        networks:
            - sail
        volumes:
            - './next:/app'
        command: ash -c "npm install && npm run dev"
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local

